# Generated by Django 4.1.7 on 2023-04-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level'], 'verbose_name_plural': 'categories'},
        ),
    ]
