# Generated by Django 4.1.7 on 2023-04-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-id'], 'verbose_name_plural': 'cases'},
        ),
    ]
