# Generated by Django 4.1.7 on 2023-04-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_case_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='user',
        ),
    ]
