# Generated by Django 4.1.7 on 2023-04-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_case_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category_name',
        ),
    ]
