name: Check style

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/dev.txt

      - name: Check style
        run: |
          pycodestyle --max-line-length=100 ./src
